
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package gramatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTEGER = 8;
  public static final int PROGRAMA = 4;
  public static final int PUNTO_COMA = 10;
  public static final int PARAMS = 9;
  public static final int VARIABLE = 13;
  public static final int EOF = 0;
  public static final int PAREN_FIN = 3;
  public static final int PAREN_INI = 2;
  public static final int error = 1;
  public static final int PROCEDIMIENTO = 5;
  public static final int DOS_PUNTOS = 11;
  public static final int FUNCION = 12;
  public static final int END = 7;
  public static final int BEGIN = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAREN_INI",
  "PAREN_FIN",
  "PROGRAMA",
  "PROCEDIMIENTO",
  "BEGIN",
  "END",
  "INTEGER",
  "PARAMS",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "FUNCION",
  "VARIABLE"
  };
}

